name: PlayerCompass
version: 1.1.0
main: dev.kmfg.plugin.PlayerCompass
api-version: 1.19
description: Tracks up to 306 players with a compass HUD
author: Kyle Yannelli

commands:
  pcc:
    description: Lists all online players and their compass marker colors.
    usage: /pcc
